name: Compilar AAB Android Firmado

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.0.0'

      - name: 3. Instalar dependencias de NPM
        run: npm install --legacy-peer-deps

      - name: 4. Exportar Next.js (Archivos estáticos)
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: 5. Sincronizar Capacitor
        run: npx cap sync android

      - name: 6. Configurar entorno Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      # --- A PARTIR DE AQUÍ SON LOS CAMBIOS PARA GOOGLE PLAY ---

      - name: 7. Compilar el AAB (Modo Producción)
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew bundleRelease

      - name: 7.5 Firmar el App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: 8. Entregar el AAB Firmado
        uses: actions/upload-artifact@v4
        with:
          name: apapacho-app-aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}